# Toxic Comment Classification Challenge

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [3]:
df['toxic'].value_counts()

0    144277
1     15294
Name: toxic, dtype: int64

In [4]:
df = df.loc[:, ['comment_text', 'toxic']]
df.head()

comment_text  toxic
0  Explanation\nWhy the edits made under my usern...      0
1  D'aww! He matches this background colour I'm s...      0
2  Hey man, I'm really not trying to edit war. It...      0
3  "\nMore\nI can't make any real suggestions on ...      0
4  You, sir, are my hero. Any chance you remember...      0

In [5]:
df.rename(columns = {'comment_text':'text', 'toxic':'targets'}, inplace = True)
df.head()

text  targets
0  Explanation\nWhy the edits made under my usern...        0
1  D'aww! He matches this background colour I'm s...        0
2  Hey man, I'm really not trying to edit war. It...        0
3  "\nMore\nI can't make any real suggestions on ...        0
4  You, sir, are my hero. Any chance you remember...        0

In [35]:
from sklearn.model_selection import train_test_split
train_df, tnv_df = train_test_split(df, test_size=0.2)
val_df, test_df = train_test_split(tnv_df, test_size=0.5)
len(train_df), len(val_df), len(test_df)


(6840, 855, 856)

In [38]:
train_df.reset_index(inplace=True)
val_df.reset_index(inplace=True)
test_df.reset_index(inplace=True)

In [39]:
train_df[3432]

KeyError: 3432

In [7]:
train_df.to_csv('train_in.csv', index=False)
val_df.to_csv('val_in.csv', index=False)
test_df.to_csv('test_in.csv', index=False)

In [ ]:
train_df.reset_index(inplace=True)

# Transformers

In [21]:
df = pd.read_csv('train_in.csv')
df.head()

text  targets
0  Explanation\nWhy the edits made under my usern...        0
1  D'aww! He matches this background colour I'm s...        0
2  Hey man, I'm really not trying to edit war. It...        0
3  "\nMore\nI can't make any real suggestions on ...        0
4  You, sir, are my hero. Any chance you remember...        0

(127656, 15957, 15958)

In [20]:
text = train_df['text'].values

In [5]:
text[0]

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [6]:
text = ["[CLS] " + txt + " [SEP]" for txt in text]
text[0]

In [8]:
from transformers import BertTokenizer, BertConfig
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)

In [10]:
tokenized_texts = [tokenizer.tokenize(txt) for txt in text]
print ("Tokenize the first sentence:")
print (tokenized_texts[0])

Tokenize the first sentence:
['[CLS]', 'explanation', 'why', 'the', 'edit', '##s', 'made', 'under', 'my', 'user', '##name', 'hardcore', 'metallic', '##a', 'fan', 'were', 'reverted', '?', 'they', 'weren', "'", 't', 'van', '##dal', '##isms', ',', 'just', 'closure', 'on', 'some', 'gas', 'after', 'i', 'voted', 'at', 'new', 'york', 'dolls', 'fa', '##c', '.', 'and', 'please', 'don', "'", 't', 'remove', 'the', 'template', 'from', 'the', 'talk', 'page', 'since', 'i', "'", 'm', 'retired', 'now', '.', '89', '.', '205', '.', '38', '.', '27', '[SEP]']


In [12]:
text1 = train_df['text'].values
tokenized_texts1 = [tokenizer.encode_plus(txt, max_length=512, truncation=True) for txt in text1]
print ("Tokenize the first sentence:")
print (tokenized_texts1[0])

Tokenize the first sentence:
{'input_ids': [101, 7526, 2339, 1996, 10086, 2015, 2081, 2104, 2026, 5310, 18442, 13076, 12392, 2050, 5470, 2020, 16407, 1029, 2027, 4694, 1005, 1056, 3158, 9305, 22556, 1010, 2074, 8503, 2006, 2070, 3806, 2044, 1045, 5444, 2012, 2047, 2259, 14421, 6904, 2278, 1012, 1998, 3531, 2123, 1005, 1056, 6366, 1996, 23561, 2013, 1996, 2831, 3931, 2144, 1045, 1005, 1049, 3394, 2085, 1012, 6486, 1012, 16327, 1012, 4229, 1012, 2676, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


In [9]:
from transformers import AdamW, BertForSequenceClassification, get_linear_schedule_with_warmup

 
model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=2).to('cuda')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [10]:
param_optimizer = list(model.named_parameters())


In [11]:
!curl -L https://raw.githubusercontent.com/Denis2054/Transformers-for-NLP-2nd-Edition/master/Chapter03/in_domain_train.tsv --output "in_domain_train.tsv"


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  428k  100  428k    0     0  1570k      0 --:--:-- --:--:-- --:--:-- 1575k


In [12]:
df = pd.read_csv("in_domain_train.tsv", delimiter='\t', header=None, names=['sentence_source', 'label', 'label_notes', 'sentence'])
df.shape

(8551, 4)

In [13]:
labels = df.label.values


In [16]:
labels[924]

0

In [17]:
import torch
labels = torch.tensor(labels)


In [18]:
labels[0]

tensor(1)

In [25]:
from typing import Tuple, Dict, List
import pathlib
import os

import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler

from transformers import BertTokenizer, BertConfig
import pdb

class TextDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_len: int = 512, eval_mode: bool = False):
        self.data = dataframe
        self.tokenizer = tokenizer
        self.text = dataframe.text
        self.eval_mode = eval_mode 
        if self.eval_mode is False:
            self.targets = dataframe.targets
        self.max_len = max_len

    def __len__(self):
        return len(self.text)

    def __getitem__(self, index):
        # text = str(self.text.iloc[index])
        # text = " ".join(text.split())
        text = str(self.text[index])

        inputs = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            padding='max_length',
            return_token_type_ids=True,
            return_attention_mask=True,
            truncation=True,
            return_tensors='pt'
        )
        
        # ids = inputs['input_ids']
        # mask = inputs['attention_mask']
        # token_type_ids = inputs["token_type_ids"]

        # output = {
        #     'ids': torch.tensor(ids, dtype=torch.long),
        #     'mask': torch.tensor(mask, dtype=torch.long),
        #     'token_type_ids': torch.tensor(token_type_ids, dtype=torch.long),
        # }
        
        ids = inputs['input_ids'].flatten()
        mask = inputs['attention_mask'].flatten()
        token_type_ids = inputs["token_type_ids"].flatten()

        output = {
            'ids': ids,
            'mask': mask,
            'token_type_ids': token_type_ids,
        }

        if self.eval_mode is False:
            output['targets'] = torch.tensor(self.targets[index], dtype=torch.long)
                
        return output

        
def datasets(train_data, train_batchsize, val_data, val_batchsize, tokenizer, max_len):


    train_dataset = TextDataset(train_data, tokenizer, max_len)
    
    val_dataset = TextDataset(val_data, tokenizer, max_len)

    train_dataloader = DataLoader(dataset=train_dataset,
                                        batch_size=train_batchsize,
                                        num_workers=0, 
                                        shuffle=True) 

    val_dataloader = DataLoader(dataset=val_dataset,
                                        batch_size=val_batchsize, 
                                        num_workers=0, 
                                        shuffle=False) 
    return train_dataloader, val_dataloader

In [20]:
TRAIN_DATA = pd.read_csv('train_in.csv')
VAL_DATA = pd.read_csv('val_in.csv')
TRAIN_BATCH=4
VAL_BATCH=4
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
MAX_LEN=512

In [21]:
train_dl, val_dl = datasets(TRAIN_DATA, TRAIN_BATCH, VAL_DATA, VAL_BATCH, tokenizer, MAX_LEN)


In [22]:
batch = next(iter(train_dl))

In [23]:
from transformers import BertForSequenceClassification, get_linear_schedule_with_warmup

model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=2)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

In [24]:
input_ids = batch['ids']
input_mask =  batch['mask']
token_type_ids =  batch['token_type_ids']
labels = batch['targets']
outputs = model(input_ids, token_type_ids=token_type_ids, attention_mask=input_mask, labels=labels)

RuntimeError: expected scalar type Long but found Int

In [18]:
outputs.keys()

odict_keys(['loss', 'logits'])

In [26]:
outputs['logits']

tensor([[ 0.2704, -0.1620],
        [ 0.4673, -0.1949],
        [ 0.1760,  0.0431],
        [ 0.5305, -0.1843]], grad_fn=<AddmmBackward0>)

In [61]:
y_pred = torch.argmax(outputs['logits'], dim=1)
y_pred

tensor([0, 0, 0, 0])

In [62]:
labels

tensor([0, 0, 0, 0], dtype=torch.int32)

In [64]:
nlaels = torch.tensor([1,0,0,0])
nlaels

tensor([1, 0, 0, 0])

In [65]:
((y_pred == nlaels).sum().item()/len(y_pred))

0.75

: 

In [29]:
val_acc=0
val_acc += ((y_pred == labels).sum().item()/len(y_pred))

In [30]:
val_acc

1.0

In [52]:
df = pd.read_csv("in_domain_train.tsv", delimiter='\t', header=None,names=['sentence_source', 'targets', 'label_notes', 'text'])
df = df.loc[:, ['text', 'targets']]
df.head()

text  targets
0  our friends wo n't buy this analysis , let alo...        1
1  one more pseudo generalization and i 'm giving...        1
2  one more pseudo generalization or i 'm giving ...        1
3   the more we study verbs , the crazier they get .        1
4         day by day the facts are getting murkier .        1

In [53]:
df.tail()

text  targets
8546               poseidon appears to own a dragon        0
8547                 digitize is my happiest memory        0
8548                it is easy to slay the gorgon .        1
8549  i had the strangest feeling that i knew you .        1
8550           what all did you get for christmas ?        1

In [54]:
train_df.reset_index(inplace=True, drop=True)
val_df.reset_index(inplace=True, drop=True)
test_df.reset_index(inplace=True, drop=True)

In [55]:
train_df.head()

level_0  index                                               text  targets
0        0   4435                the children are seen in the yard .        1
1        1   6015                   he will eat deep fried muffins .        1
2        2   2283                 the garden is swarming with bees .        1
3        3   3329  on the comer of the two boulevards stood a sta...        1
4        4   6684                  frank bought something for jane .        1

In [56]:
len(train_df)

6840

In [57]:
text = train_df.text

In [58]:
len(text)

6840

In [59]:
text[6359]

'networking helps you grow your business .'

In [50]:
len(train_df)

6840

In [51]:
train_df[6358:]

level_0  index                                               text  \
6358     6358   5183                   i would dance with mary or sue .   
6359     6359   5760          networking helps you grow your business .   
6360     6360   8356                             she tried to may leave   
6361     6361   6420  john bought any picture of queen elizabeth tha...   
6362     6362   5950                   i think if john likes his beer .   
...       ...    ...                                                ...   
6835     6835   7592                 mary considers john proud of her .   
6836     6836   1643     i brought a razor with which to shave myself .   
6837     6837   2999                        tourists admire paintings .   
6838     6838   4099  why do n't you leaving me concentrate on my wo...   
6839     6839   2620            doug removed the scratches to nowhere .   

      targets  
6358        1  
6359        1  
6360        0  
6361        1  
6362        0  
...       ...  
6835        1  
6836        1  
6837        1  
6838        0  
6839        0  

[482 rows x 4 columns]

In [60]:
train_df.to_csv('train_in1.csv', index=False)
val_df.to_csv('val_in1.csv', index=False)
test_df.to_csv('test_in1.csv', index=False)